# Generated by Django 6.0.3 on 2026-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tracking_speed_kmh'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
