# Generated by Django 6.0.4 on 2026-05-30 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('picked', 'Recogido'), ('not_picked', 'No recogido'), ('dropped_off', 'Dejado en parada')], default='not_picked', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('route_started', 'Ruta iniciada'), ('student_picked_up', 'Estudiante recogido'), ('student_dropped_off', 'Estudiante dejado en parada'), ('approaching_stop', 'Bus aproximandose a parada'), ('approaching_destination', 'Bus aproximandose al destino'), ('driver_near_stop', 'Conductor proximo a parada'), ('driver_near_destination', 'Conductor proximo al destino final')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', 'created_at'], name='users_notif_user_id_1308e8_idx')],
            },
        ),
    ]
