name: Deploy Backend - Vialtros

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Subir backend a carpeta temporal
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "backend/*"
          target: "/tmp/vialtros_api"
          strip_components: 1
          rm: false
          overwrite: true

      - name: Configurar backend Django
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            DEPLOY_USER=$(id -un)

            # Mover archivos al destino final con permisos elevados
            sudo mkdir -p /var/www/ds1/Vialtros/api
            sudo cp -rf /tmp/vialtros_api/. /var/www/ds1/Vialtros/api/
            sudo chown -R "$DEPLOY_USER:$DEPLOY_USER" /var/www/ds1/Vialtros/api
            rm -rf /tmp/vialtros_api

            cd /var/www/ds1/Vialtros/api

            # Crear entorno virtual si no existe
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            source .venv/bin/activate

            pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart daphne

            echo "Backend desplegado correctamente"
